"""@brief Docker 部署配置的回归测试 / Regression tests for Docker deployment configuration."""

from __future__ import annotations

import stat
from contextlib import chdir
from pathlib import Path
from typing import Any

import json5
import pytest

from backend.config import BackendSettings
from dashboard.infrastructure.config import DashboardSettings
from dbctl.infrastructure.runtime_projection import build_runtime_config, write_runtime_config
from dbctl.interfaces.cli import main as dbctl_main
from workspace_shared.jsonc import ConfigurationError

PROJECT_ROOT = Path(__file__).resolve().parents[1]
"""@brief 仓库根目录 / Repository root."""


def _container_environment() -> dict[str, str]:
    """@brief 构造不含数据库密码的容器测试环境 / Build a container environment without database passwords.

    @return 生产身份与非数据库覆盖 / Production identity and non-database overrides.
    """

    return {
        "AIWS_ENVIRONMENT": "production",
        "AIWS_PUBLIC_BASE_URL": "https://workspace.example.test",
        "AIWS_IDENTITY_MODE": "trusted_proxy_hmac",
        "AIWS_TRUSTED_PROXY_HMAC_SECRET": "test-only-hmac-secret-with-at-least-32-bytes",
        "AIWS_TRUSTED_PROXY_CIDRS": '["172.30.0.0/24"]',
    }


def _bootstrap_config(tmp_path: Path) -> Path:
    """@brief 仅通过 dbctl 初始化 Docker 持久配置 / Initialize Docker persistent config only through dbctl.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @return dbctl 生成的 config.jsonc 路径 / Path to config.jsonc generated by dbctl.
    """

    config_path = tmp_path / "config.jsonc"
    with chdir(tmp_path):
        exit_code = dbctl_main(
            [
                "--dbinit",
                str(PROJECT_ROOT / "deploy/docker/dbinit.jsonc"),
                "bootstrap",
                "--dry-run",
            ]
        )
    assert exit_code == 0
    return config_path


def _load_mapping(path: Path) -> dict[str, Any]:
    """@brief 加载测试 JSONC 对象 / Load a test JSONC object.

    @param path JSONC 路径 / JSONC path.
    @return 可变根对象 / Mutable root object.
    """

    parsed = json5.loads(path.read_text(encoding="utf-8"))
    assert isinstance(parsed, dict)
    return parsed


def test_runtime_projection_preserves_dbctl_credentials(tmp_path: Path) -> None:
    """@brief 运行投影必须保留 dbctl 凭证且满足所有进程 / Projection preserves dbctl credentials and satisfies every process.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @return 无返回值 / No return value.
    """

    source_path = _bootstrap_config(tmp_path)
    runtime_path = tmp_path / "runtime/config.jsonc"
    source = _load_mapping(source_path)
    write_runtime_config(source_path, runtime_path, _container_environment())
    runtime = _load_mapping(runtime_path)

    assert runtime["database"]["application_dsn"] == source["database"]["application_dsn"]
    assert runtime["database"]["migrator_dsn"] == source["database"]["migrator_dsn"]
    assert runtime["database"]["dashboard_dsn"] == source["database"]["dashboard_dsn"]
    assert "@postgres:5432/ai_job_workspace" in runtime["database"]["application_dsn"]

    backend = BackendSettings.from_file(runtime_path)
    dashboard = DashboardSettings.from_file(runtime_path)
    assert backend.environment == "production"
    assert backend.database.mode == "postgresql"
    assert backend.network.bind_host == "0.0.0.0"
    assert backend.security.identity_mode == "trusted_proxy_hmac"
    assert dashboard.database.mode == "postgresql"
    assert dashboard.api.host == "0.0.0.0"
    assert dashboard.access.mode == "operator_token"
    assert stat.S_IMODE(source_path.stat().st_mode) == 0o600
    assert stat.S_IMODE(runtime_path.stat().st_mode) == 0o600


def test_container_entrypoint_requires_dbctl_bootstrap(tmp_path: Path) -> None:
    """@brief 缺少 dbctl 配置时容器不得代为生成 / Container must not generate a missing dbctl config.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    """

    missing_path = tmp_path / "config.jsonc"
    with pytest.raises(ConfigurationError, match="dbctl bootstrap"):
        build_runtime_config(missing_path, _container_environment())
    assert not missing_path.exists()


def test_default_runtime_projection_keeps_development_mocks(tmp_path: Path) -> None:
    """@brief 默认投影保留开发 mock 且启用 PostgreSQL / Default projection keeps development mocks with PostgreSQL.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    """

    source_path = _bootstrap_config(tmp_path)
    runtime = build_runtime_config(source_path, {})

    assert runtime["environment"] == "development"
    assert runtime["database"]["mode"] == "postgresql"
    assert runtime["security"]["identity_mode"] == "development_mock"
    assert runtime["ai"]["provider"] == "mock"
    assert runtime["resume_rendering"]["adapter"] == "mock"


def test_docker_dbinit_only_changes_connection_endpoint() -> None:
    """@brief Docker dbinit 只能改变连接端点 / Docker dbinit may only change the connection endpoint."""

    local = _load_mapping(PROJECT_ROOT / "dbinit.jsonc")
    docker = _load_mapping(PROJECT_ROOT / "deploy/docker/dbinit.jsonc")

    assert docker["database_connection"] == {"host": "postgres", "port": 5432}
    assert docker["database_administration"] == local["database_administration"]


def test_production_container_requires_hmac_secret(tmp_path: Path) -> None:
    """@brief 生产容器缺少 HMAC secret 时必须 fail closed / Production container fails closed without HMAC."""

    source_path = _bootstrap_config(tmp_path)
    environ = _container_environment()
    del environ["AIWS_TRUSTED_PROXY_HMAC_SECRET"]

    with pytest.raises(ConfigurationError, match="AIWS_TRUSTED_PROXY_HMAC_SECRET"):
        build_runtime_config(source_path, environ)
