"""@brief Docker 部署配置的回归测试 / Regression tests for Docker deployment configuration."""

from __future__ import annotations

import errno
import json
import os
import stat
from collections.abc import Mapping
from contextlib import chdir
from pathlib import Path
from typing import Any

import json5
import pytest

from backend.config import BackendSettings
from dashboard.infrastructure.config import DashboardSettings
from dbctl.application.container_startup import ContainerLaunchError, ContainerStartupService
from dbctl.infrastructure.container_runtime import ContainerRuntimeAdapter
from dbctl.infrastructure.runtime_projection import build_runtime_config, write_runtime_config
from dbctl.interfaces import container as container_entrypoint
from dbctl.interfaces.cli import main as dbctl_main
from workspace_shared.jsonc import ConfigurationError

PROJECT_ROOT = Path(__file__).resolve().parents[1]
"""@brief 仓库根目录 / Repository root."""


def _container_environment() -> dict[str, str]:
    """@brief 构造不含数据库密码的容器测试环境 / Build a container environment without database passwords.

    @return 生产身份与非数据库覆盖 / Production identity and non-database overrides.
    """

    return {
        "AIWS_ENVIRONMENT": "production",
        "AIWS_PUBLIC_BASE_URL": "https://api.hmalliances.org:8022",
        "AIWS_IDENTITY_MODE": "disabled",
        "AIWS_CURSOR_HMAC_SECRET": "test-only-cursor-secret-with-at-least-32-bytes",
        "AIWS_SENSITIVE_IDEMPOTENCY_HMAC_SECRET": (
            "test-only-sensitive-idempotency-secret-32-bytes"
        ),
        "AIWS_IDENTITY_EMAIL_ACTIVE_KEY_ID": "email-key-2026-07",
        "AIWS_IDENTITY_EMAIL_ENCRYPTION_KEYS": (
            '{"email-key-2026-07":"BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwc"}'
        ),
        "AIWS_IDENTITY_EMAIL_RATE_LIMIT_HMAC_KEY": (
            "CQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQk"
        ),
        "AIWS_IDENTITY_EMAIL_FROM_ADDRESS": "identity@example.test",
        "AIWS_IDENTITY_EMAIL_SMTP_HOST": "smtp.example.test",
        "AIWS_TRUSTED_PROXY_CIDRS": '["172.30.0.0/24"]',
        "AIWS_DASHBOARD_OPERATOR_TOKEN": "test-only-dashboard-token",
        "AIWS_AI_PROVIDER": "openai-compatible",
        "AIWS_AI_MODEL": "production-chat-model",
        "AIWS_AI_BASE_URL": "https://models.example.test/v1",
        "AIWS_AI_DATA_REGION": "private_deployment",
        "AIWS_AI_EMBEDDING_PROVIDER": "openai-compatible",
        "AIWS_AI_EMBEDDING_MODEL": "production-embedding-model",
        "AIWS_AI_EMBEDDING_MODEL_REVISION": "2026-07",
        "AIWS_AI_EMBEDDING_DIMENSION": "1024",
        "AIWS_LLM_API_KEY": "test-only-model-key",
        "AIWS_RESUME_RENDERER_ADAPTER": "xelatex",
        "AIWS_RESUME_XELATEX_COMMAND": "xelatex",
        "AIWS_KNOWLEDGE_PROVIDER_SESSION_ACTIVE_KEY_ID": "launch-key-2026-07",
        "AIWS_KNOWLEDGE_PROVIDER_SESSION_KEYS": (
            '{"launch-key-2026-07":"CgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo"}'
        ),
        "AIWS_KNOWLEDGE_CREDENTIAL_ACTIVE_KEY_ID": "vault-key-2026-07",
        "AIWS_KNOWLEDGE_CREDENTIAL_KEYS": (
            '{"vault-key-2026-07":"CwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCws"}'
        ),
        "AIWS_KNOWLEDGE_CREDENTIAL_FINGERPRINT_HMAC_KEY": (
            "DAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw"
        ),
        "AIWS_KNOWLEDGE_CREDENTIAL_REFERENCE_HMAC_KEY": (
            "DQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0"
        ),
        "AIWS_KNOWLEDGE_S3_ENDPOINT": "https://objects.example.test",
        "AIWS_KNOWLEDGE_S3_REGION": "private-deployment-1",
        "AIWS_KNOWLEDGE_S3_BUCKET": "aiws-knowledge",
        "AIWS_KNOWLEDGE_S3_ACCESS_KEY_ID": "test-only-access-key",
        "AIWS_KNOWLEDGE_S3_SECRET_ACCESS_KEY": "test-only-secret-access-key",
        "AIWS_KNOWLEDGE_MALWARE_MODE": "reject",
        "AIWS_KNOWLEDGE_SOURCE_ALLOWED_HOST_PATTERNS": (
            '["example.test","*.example.test"]'
        ),
        "AIWS_INTERVIEW_REALTIME_ACTIVE_KEY_ID": "interview-key-2026-07",
        "AIWS_INTERVIEW_REALTIME_SIGNING_KEYS": (
            '{"interview-key-2026-07":"FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQ"}'
        ),
        "AIWS_INTERVIEW_SIGNALING_URL": (
            "wss://realtime.hmalliances.org/v2/interview"
        ),
        "AIWS_INTERVIEW_ICE_URLS": (
            '["stun:stun.hmalliances.org:3478",'
            '"turns:turn.hmalliances.org:5349?transport=tcp"]'
        ),
    }


def _bootstrap_config(tmp_path: Path) -> Path:
    """@brief 仅通过 dbctl 初始化 Docker 持久配置 / Initialize Docker persistent config only through dbctl.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @return dbctl 生成的 config.jsonc 路径 / Path to config.jsonc generated by dbctl.
    """

    config_path = tmp_path / "config.jsonc"
    with chdir(tmp_path):
        exit_code = dbctl_main(
            [
                "--dbinit",
                str(PROJECT_ROOT / "deploy/docker/dbinit.jsonc"),
                "bootstrap",
                "--dry-run",
            ]
        )
    assert exit_code == 0
    return config_path


def _load_mapping(path: Path) -> dict[str, Any]:
    """@brief 加载测试 JSONC 对象 / Load a test JSONC object.

    @param path JSONC 路径 / JSONC path.
    @return 可变根对象 / Mutable root object.
    """

    parsed = json5.loads(path.read_text(encoding="utf-8"))
    assert isinstance(parsed, dict)
    return parsed


def test_runtime_projection_preserves_dbctl_credentials(tmp_path: Path) -> None:
    """@brief 运行投影必须保留 dbctl 凭证且满足所有进程 / Projection preserves dbctl credentials and satisfies every process.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @return 无返回值 / No return value.
    """

    source_path = _bootstrap_config(tmp_path)
    runtime_path = tmp_path / "runtime/config.jsonc"
    source = _load_mapping(source_path)
    write_runtime_config(source_path, runtime_path, _container_environment())
    runtime = _load_mapping(runtime_path)

    assert runtime["database"]["application_dsn"] == source["database"]["application_dsn"]
    assert runtime["database"]["migrator_dsn"] == source["database"]["migrator_dsn"]
    assert runtime["database"]["dashboard_dsn"] == source["database"]["dashboard_dsn"]
    assert "@postgres:5432/ai_job_workspace" in runtime["database"]["application_dsn"]

    backend = BackendSettings.from_file(runtime_path)
    dashboard = DashboardSettings.from_file(runtime_path)
    assert backend.environment == "production"
    assert backend.database.mode == "postgresql"
    assert backend.network.bind_host == "0.0.0.0"
    assert backend.network.bind_port == 9000
    assert backend.network.public_base_url == "https://api.hmalliances.org:8022"
    assert not backend.api.legacy_v1_enabled
    assert backend.security.identity_mode == "disabled"
    assert backend.security.trusted_proxy_hmac_secret is None
    assert backend.security.cursor_hmac_secret == (
        "test-only-cursor-secret-with-at-least-32-bytes"
    )
    assert backend.security.sensitive_idempotency_hmac_secret == (
        "test-only-sensitive-idempotency-secret-32-bytes"
    )
    assert backend.hosted_identity.email.outbox.active_key_id == "email-key-2026-07"
    assert backend.hosted_identity.email.outbox.encryption_keys[0].key == bytes([7]) * 32
    assert backend.hosted_identity.email.outbox.rate_limit_hmac_key == bytes([9]) * 32
    assert backend.hosted_identity.email.mode == "smtp"
    assert backend.hosted_identity.email.smtp_host == "smtp.example.test"
    assert backend.hosted_identity.password_breach.mode == "pwned_passwords"
    assert backend.ai.api_key == "test-only-model-key"
    assert backend.ai.provider == "openai-compatible"
    assert backend.ai.embedding_provider == "openai-compatible"
    assert backend.renderer.adapter == "xelatex"
    assert backend.knowledge.connections.provider_session_keyring.active_key_id == (
        "launch-key-2026-07"
    )
    assert backend.knowledge.connections.credential_keyring.active_key_id == "vault-key-2026-07"
    assert backend.knowledge.uploads.storage.mode == "s3"
    assert backend.knowledge.uploads.malware.mode == "reject"
    assert backend.knowledge.source_network.allowed_host_patterns == (
        "example.test",
        "*.example.test",
    )
    assert backend.interview.realtime.signing_keyring.active_key_id == (
        "interview-key-2026-07"
    )
    assert backend.interview.realtime.active_signing_key == bytes([20]) * 32
    assert backend.interview.realtime.signaling_url == (
        "wss://realtime.hmalliances.org/v2/interview"
    )
    assert backend.interview.realtime.ice_urls[1].startswith("turns:")
    assert dashboard.database.mode == "postgresql"
    assert dashboard.api.host == "0.0.0.0"
    assert dashboard.access.mode == "operator_token"
    assert dashboard.access.token == "test-only-dashboard-token"
    assert stat.S_IMODE(source_path.stat().st_mode) == 0o600
    assert stat.S_IMODE(runtime_path.stat().st_mode) == 0o600


@pytest.mark.parametrize(
    ("environment_name", "mock_value", "message"),
    (
        ("AIWS_RESUME_RENDERER_ADAPTER", "mock", r"resume_rendering\.adapter"),
        ("AIWS_AI_PROVIDER", "mock", r"ai\.provider/model"),
        ("AIWS_AI_EMBEDDING_PROVIDER", "mock", r"ai\.embedding_provider/model"),
    ),
)
def test_production_projection_cannot_enable_mock_product_capabilities(
    tmp_path: Path,
    environment_name: str,
    mock_value: str,
    message: str,
) -> None:
    """@brief 投影后的生产配置拒绝返回假成功的 mock / Projected production config rejects mocks that manufacture success.

    @param tmp_path pytest 临时目录 / pytest temporary directory.
    @param environment_name 被污染的环境变量 / Environment variable being corrupted.
    @param mock_value 非法 mock 值 / Invalid mock value.
    @param message 预期安全错误字段 / Expected safe error field.
    """

    source_path = _bootstrap_config(tmp_path)
    environ = _container_environment()
    environ[environment_name] = mock_value
    runtime = build_runtime_config(source_path, environ)
    runtime_path = tmp_path / f"runtime-{environment_name}.json"
    runtime_path.write_text(json.dumps(runtime), encoding="utf-8")

    with pytest.raises(ConfigurationError, match=message):
        BackendSettings.from_file(runtime_path)


def test_container_entrypoint_requires_dbctl_bootstrap(tmp_path: Path) -> None:
    """@brief 缺少 dbctl 配置时容器不得代为生成 / Container must not generate a missing dbctl config.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    """

    missing_path = tmp_path / "config.jsonc"
    with pytest.raises(ConfigurationError, match="dbctl bootstrap"):
        build_runtime_config(missing_path, _container_environment())
    assert not missing_path.exists()


def test_container_entrypoint_without_command_preserves_exact_error(
    capsys: pytest.CaptureFixture[str],
) -> None:
    """@brief 空命令保持既有精确错误与状态 2 / Empty command preserves the exact error and status two.

    @param capsys pytest 标准流捕获器 / Pytest standard-stream capture.
    @return 无返回值 / No return value.
    """

    assert container_entrypoint.main([]) == 2
    captured = capsys.readouterr()
    assert captured.out == ""
    assert captured.err == "container entrypoint requires a command\n"


def test_container_use_case_rejects_empty_command_before_projection(tmp_path: Path) -> None:
    """@brief 应用层空 argv 在任何投影前失败 / Application rejects empty argv before projection.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @return 无返回值 / No return value.
    """

    class ForbiddenRuntimePort:
        """@brief 任何外部调用都表示不变量检查过晚 / Any external call means validation was late."""

        def project(
            self,
            _source: Path,
            _runtime: Path,
            _environ: Mapping[str, str],
        ) -> None:
            """@brief 拒绝空命令触发配置投影 / Reject projection for an empty command.

            @param _source 未使用持久路径 / Unused persistent path.
            @param _runtime 未使用运行路径 / Unused runtime path.
            @param _environ 未使用环境 / Unused environment.
            @return 永不返回 / Never returns.
            """

            pytest.fail("空命令不得投影运行配置")

        def replace(
            self,
            _command: tuple[str, ...],
            _environ: Mapping[str, str],
        ) -> None:
            """@brief 拒绝空命令触发进程替换 / Reject replacement for an empty command.

            @param _command 未使用 argv / Unused argv.
            @param _environ 未使用环境 / Unused environment.
            @return 永不返回 / Never returns.
            """

            pytest.fail("空命令不得替换进程")

    service = ContainerStartupService(ForbiddenRuntimePort())

    with pytest.raises(ContainerLaunchError, match="运行配置未投影"):
        service.execute(
            tmp_path / "source.jsonc",
            tmp_path / "runtime.jsonc",
            (),
            {},
            source_overridden=False,
            runtime_overridden=False,
        )


def test_container_entrypoint_projects_before_successful_exec(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """@brief 入口必须先明示投影，再原样 exec 目标命令 / Entrypoint explicitly projects before execing the target unchanged.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @param monkeypatch pytest 故障注入器 / Pytest fault injector.
    @param capsys pytest 标准流捕获器 / Pytest standard-stream capture.
    @return 无返回值 / No return value.
    """

    source_path = tmp_path / "persistent/config.jsonc"
    runtime_path = tmp_path / "runtime/config.jsonc"
    command = ("backend-server", "--serve")
    calls: list[str] = []

    def fake_write_runtime_config(
        _adapter: ContainerRuntimeAdapter,
        source: Path,
        runtime: Path,
        environ: Mapping[str, str],
    ) -> None:
        """@brief 记录投影参数 / Record projection parameters.

        @param _adapter 未使用的运行时适配器 / Unused runtime adapter.
        @param source 持久配置路径 / Persistent-configuration path.
        @param runtime 运行投影路径 / Runtime-projection path.
        @param environ 容器环境 / Container environment.
        @return 无返回值 / No return value.
        """

        calls.append("project")
        assert source == source_path
        assert runtime == runtime_path
        assert environ is os.environ

    def fake_execvpe(
        _adapter: ContainerRuntimeAdapter,
        arguments: tuple[str, ...],
        environ: Mapping[str, str],
    ) -> None:
        """@brief 记录保持原样的 exec 边界 / Record the unchanged exec boundary.

        @param _adapter 未使用的运行时适配器 / Unused runtime adapter.
        @param arguments 未改写的 argv / Unmodified argv.
        @param environ 容器环境 / Container environment.
        @return 无返回值 / No return value.
        """

        calls.append("exec")
        assert arguments == command
        assert environ is os.environ

    monkeypatch.setenv("AIWS_SOURCE_CONFIG", str(source_path))
    monkeypatch.setenv("AIWS_CONFIG", str(runtime_path))
    monkeypatch.setattr(ContainerRuntimeAdapter, "project", fake_write_runtime_config)
    monkeypatch.setattr(ContainerRuntimeAdapter, "replace", fake_execvpe)

    assert container_entrypoint.main(command) == 0

    captured = capsys.readouterr()
    assert captured.out == ""
    assert calls == ["project", "exec"]
    assert "投影容器运行配置" in captured.err
    assert "容器运行配置已原子投影" in captured.err
    assert "以 exec 替换容器入口进程" in captured.err
    assert "argv=2 项" in captured.err
    assert "命令与参数内容不回显" in captured.err
    assert str(source_path) not in captured.err
    assert str(runtime_path) not in captured.err


def test_container_runtime_adapter_execvpe_preserves_argv_and_environment(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """@brief 运行时适配器保持 executable、argv 与环境身份 / Runtime adapter preserves executable, argv, and environment identity.

    @param monkeypatch pytest 故障注入器 / Pytest fault injector.
    @return 无返回值 / No return value.
    """

    command = ("backend-server", "--serve", "--workers=2")
    environment = {"AIWS_ENVIRONMENT": "production"}
    calls: list[tuple[str, tuple[str, ...], Mapping[str, str]]] = []

    def fake_execvpe(
        executable: str,
        arguments: tuple[str, ...],
        environ: Mapping[str, str],
    ) -> None:
        """@brief 记录原生 execvpe 调用 / Record the native execvpe call.

        @param executable 目标可执行文件 / Target executable.
        @param arguments 保持原样的 argv / Unmodified argv.
        @param environ 保持原样的环境 / Unmodified environment.
        @return 无返回值 / No return value.
        """

        calls.append((executable, arguments, environ))

    monkeypatch.setattr(os, "execvpe", fake_execvpe)

    ContainerRuntimeAdapter().replace(command, environment)

    assert calls == [(command[0], command, environment)]
    assert calls[0][2] is environment


def test_container_entrypoint_missing_config_has_safe_traceback(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """@brief 缺失持久配置时返回 2 并给出可行动的安全栈 / Missing persistent config returns two with an actionable safe stack.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @param monkeypatch pytest 故障注入器 / Pytest fault injector.
    @param capsys pytest 标准流捕获器 / Pytest standard-stream capture.
    @return 无返回值 / No return value.
    """

    missing_path = tmp_path / "missing-config.jsonc"
    runtime_path = tmp_path / "runtime/config.jsonc"

    def forbidden_execvpe(
        _adapter: ContainerRuntimeAdapter,
        _arguments: tuple[str, ...],
        _environ: Mapping[str, str],
    ) -> None:
        """@brief 拒绝在投影失败后启动进程 / Reject process launch after projection failure.

        @param _adapter 未使用的运行时适配器 / Unused runtime adapter.
        @param _arguments 未使用 argv / Unused argv.
        @param _environ 未使用环境 / Unused environment.
        @return 永不返回 / Never returns.
        """

        pytest.fail("缺失配置时不得调用 execvpe")

    monkeypatch.setenv("AIWS_SOURCE_CONFIG", str(missing_path))
    monkeypatch.setenv("AIWS_CONFIG", str(runtime_path))
    monkeypatch.setattr(ContainerRuntimeAdapter, "replace", forbidden_execvpe)

    assert container_entrypoint.main(["backend-server"]) == 2

    captured = capsys.readouterr()
    assert captured.out == ""
    assert "容器运行配置投影失败" in captured.err
    assert "目标进程尚未启动" in captured.err
    assert "Traceback（已脱敏" in captured.err
    assert "ContainerProjectionError" in captured.err
    assert "ExternalDiagnosticError" in captured.err
    assert "底层异常类别=builtins.ValueError" in captured.err
    assert "workspace_shared.jsonc.ConfigurationError" not in captured.err
    assert "run dbctl bootstrap before starting container services" not in captured.err
    assert "请先运行 `dbctl bootstrap`" in captured.err
    assert str(missing_path) not in captured.err


def test_container_entrypoint_exec_failure_is_safe_and_preserves_runtime_projection(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """@brief exec 失败必须保留状态 1 且隐藏 secret、notes 与控制字符 / Exec failure preserves status one and hides secrets, notes, and controls.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @param monkeypatch pytest 故障注入器 / Pytest fault injector.
    @param capsys pytest 标准流捕获器 / Pytest standard-stream capture.
    @return 无返回值 / No return value.
    """

    opaque_secret = "opaque-container-secret"
    forged_line = "FORGED-SUCCESS-LINE"
    source_path = tmp_path / f"source-{opaque_secret}\x1b[31m.jsonc"
    runtime_path = tmp_path / f"runtime-{opaque_secret}\x1b[2J.jsonc"
    raw_error = FileNotFoundError(
        errno.ENOENT,
        f"{opaque_secret}\x1b[31m{forged_line}",
    )
    raw_error.add_note(
        f"postgresql://operator:{opaque_secret}@db.example.test:5432/aiws\n{forged_line}"
    )

    def fake_write_runtime_config(
        _adapter: ContainerRuntimeAdapter,
        _source: Path,
        _runtime: Path,
        _environ: Mapping[str, str],
    ) -> None:
        """@brief 模拟已完成的原子投影 / Simulate a completed atomic projection.

        @param _adapter 未使用的运行时适配器 / Unused runtime adapter.
        @param _source 未使用持久路径 / Unused persistent path.
        @param _runtime 未使用运行路径 / Unused runtime path.
        @param _environ 未使用环境 / Unused environment.
        @return 无返回值 / No return value.
        """

    def failing_execvpe(
        _adapter: ContainerRuntimeAdapter,
        _arguments: tuple[str, ...],
        _environ: Mapping[str, str],
    ) -> None:
        """@brief 注入含敏感消息与伪造 notes 的 exec 失败 / Inject exec failure with sensitive text and forged notes.

        @param _adapter 未使用的运行时适配器 / Unused runtime adapter.
        @param _arguments 未使用 argv / Unused argv.
        @param _environ 未使用环境 / Unused environment.
        @return 永不返回 / Never returns.
        @raise FileNotFoundError 固定含敏感内容的启动失败 / Fixed launch failure with sensitive content.
        """

        raise raw_error

    monkeypatch.setenv("AIWS_SOURCE_CONFIG", str(source_path))
    monkeypatch.setenv("AIWS_CONFIG", str(runtime_path))
    monkeypatch.setattr(ContainerRuntimeAdapter, "project", fake_write_runtime_config)
    monkeypatch.setattr(ContainerRuntimeAdapter, "replace", failing_execvpe)

    assert (
        container_entrypoint.main(
            ["backend-server", f"--token={opaque_secret}", f"\x1b[32m{forged_line}"]
        )
        == 1
    )

    captured = capsys.readouterr()
    assert captured.out == ""
    assert "容器运行配置已原子投影" in captured.err
    assert "容器目标进程启动失败" in captured.err
    assert "运行配置已投影" in captured.err
    assert "目标进程未启动" in captured.err
    assert "ExternalDiagnosticError" in captured.err
    assert "builtins.FileNotFoundError" in captured.err
    assert "errno=2" in captured.err
    assert "命令是否存在及容器用户执行权限" in captured.err
    assert opaque_secret not in captured.err
    assert forged_line not in captured.err
    assert "postgresql://" not in captured.err
    assert "\x1b" not in captured.err


def test_container_entrypoint_unknown_projection_failure_hides_untrusted_diagnostics(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """@brief 未知投影故障保留栈和部分状态但隐藏任意文本 / Unknown projection failure preserves stack and partial state while hiding arbitrary text.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @param monkeypatch pytest 故障注入器 / Pytest fault injector.
    @param capsys pytest 标准流捕获器 / Pytest standard-stream capture.
    @return 无返回值 / No return value.
    """

    opaque_secret = "unknown-projection-secret"
    forged_line = "FORGED-PROJECTION-SUCCESS"
    raw_error = RuntimeError(f"{opaque_secret}\x1b[2J{forged_line}")
    raw_error.add_note(
        f"postgresql://operator:{opaque_secret}@db.example.test:5432/aiws\n{forged_line}"
    )
    calls: list[str] = []

    def failing_project(
        _adapter: ContainerRuntimeAdapter,
        _source: Path,
        _runtime: Path,
        _environ: Mapping[str, str],
    ) -> None:
        """@brief 注入含任意文本的未知投影故障 / Inject an unknown projection failure with arbitrary text.

        @param _adapter 未使用的运行时适配器 / Unused runtime adapter.
        @param _source 未使用持久路径 / Unused persistent path.
        @param _runtime 未使用运行路径 / Unused runtime path.
        @param _environ 未使用环境 / Unused environment.
        @return 永不返回 / Never returns.
        @raise RuntimeError 固定未知故障 / Fixed unknown failure.
        """

        calls.append("project")
        raise raw_error

    def forbidden_replace(
        _adapter: ContainerRuntimeAdapter,
        _arguments: tuple[str, ...],
        _environ: Mapping[str, str],
    ) -> None:
        """@brief 拒绝在未知投影故障后替换进程 / Reject replacement after unknown projection failure.

        @param _adapter 未使用的运行时适配器 / Unused runtime adapter.
        @param _arguments 未使用 argv / Unused argv.
        @param _environ 未使用环境 / Unused environment.
        @return 永不返回 / Never returns.
        """

        pytest.fail("投影失败后不得替换进程")

    source_path = tmp_path / f"source-{opaque_secret}\x1b[31m.jsonc"
    runtime_path = tmp_path / f"runtime-{opaque_secret}\x1b[2J.jsonc"
    monkeypatch.setenv("AIWS_SOURCE_CONFIG", str(source_path))
    monkeypatch.setenv("AIWS_CONFIG", str(runtime_path))
    monkeypatch.setattr(ContainerRuntimeAdapter, "project", failing_project)
    monkeypatch.setattr(ContainerRuntimeAdapter, "replace", forbidden_replace)

    assert container_entrypoint.main(["backend-server", f"--token={opaque_secret}"]) == 1

    captured = capsys.readouterr()
    assert captured.out == ""
    assert calls == ["project"]
    assert "容器运行配置投影失败" in captured.err
    assert "运行配置投影未报告完成" in captured.err
    assert "目标进程尚未启动" in captured.err
    assert "未预期的 builtins.RuntimeError" in captured.err
    assert "builtins.RuntimeError" in captured.err
    assert "容器运行配置已原子投影" not in captured.err
    assert opaque_secret not in captured.err
    assert forged_line not in captured.err
    assert "postgresql://" not in captured.err
    assert "\x1b" not in captured.err


def test_container_entrypoint_unknown_launch_failure_reports_completed_projection_safely(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """@brief 未知 exec 故障隐藏任意文本并明确投影已完成 / Unknown exec failure hides arbitrary text and states projection completion.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @param monkeypatch pytest 故障注入器 / Pytest fault injector.
    @param capsys pytest 标准流捕获器 / Pytest standard-stream capture.
    @return 无返回值 / No return value.
    """

    opaque_secret = "unknown-launch-secret"
    forged_line = "FORGED-LAUNCH-SUCCESS"
    raw_error = RuntimeError(f"{opaque_secret}\x1b]2;{forged_line}\x07")
    raw_error.add_note(f"password={opaque_secret}\n{forged_line}\x1b[32m")
    calls: list[str] = []

    def successful_project(
        _adapter: ContainerRuntimeAdapter,
        _source: Path,
        _runtime: Path,
        environ: Mapping[str, str],
    ) -> None:
        """@brief 记录成功投影 / Record a successful projection.

        @param _adapter 未使用的运行时适配器 / Unused runtime adapter.
        @param _source 未使用持久路径 / Unused persistent path.
        @param _runtime 未使用运行路径 / Unused runtime path.
        @param environ 保持原样的环境 / Unmodified environment.
        @return 无返回值 / No return value.
        """

        calls.append("project")
        assert environ is os.environ

    def failing_replace(
        _adapter: ContainerRuntimeAdapter,
        arguments: tuple[str, ...],
        environ: Mapping[str, str],
    ) -> None:
        """@brief 注入含任意文本的未知 exec 故障 / Inject an unknown exec failure with arbitrary text.

        @param _adapter 未使用的运行时适配器 / Unused runtime adapter.
        @param arguments 保持原样的 argv / Unmodified argv.
        @param environ 保持原样的环境 / Unmodified environment.
        @return 永不返回 / Never returns.
        @raise RuntimeError 固定未知故障 / Fixed unknown failure.
        """

        calls.append("exec")
        assert arguments == ("backend-server", f"--token={opaque_secret}")
        assert environ is os.environ
        raise raw_error

    monkeypatch.setenv("AIWS_SOURCE_CONFIG", str(tmp_path / "source.jsonc"))
    monkeypatch.setenv("AIWS_CONFIG", str(tmp_path / "runtime.jsonc"))
    monkeypatch.setattr(ContainerRuntimeAdapter, "project", successful_project)
    monkeypatch.setattr(ContainerRuntimeAdapter, "replace", failing_replace)

    assert container_entrypoint.main(["backend-server", f"--token={opaque_secret}"]) == 1

    captured = capsys.readouterr()
    assert captured.out == ""
    assert calls == ["project", "exec"]
    assert "容器运行配置已原子投影" in captured.err
    assert "容器目标进程启动失败" in captured.err
    assert "运行配置已原子投影" in captured.err
    assert "目标进程尚未启动" in captured.err
    assert "未预期的 builtins.RuntimeError" in captured.err
    assert "builtins.RuntimeError" in captured.err
    assert opaque_secret not in captured.err
    assert forged_line not in captured.err
    assert "password=" not in captured.err
    assert "\x1b" not in captured.err


def test_default_runtime_projection_keeps_development_mocks(tmp_path: Path) -> None:
    """@brief 默认投影保留开发 mock 且启用 PostgreSQL / Default projection keeps development mocks with PostgreSQL.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    """

    source_path = _bootstrap_config(tmp_path)
    runtime = build_runtime_config(
        source_path,
        {
            "AIWS_KNOWLEDGE_LOCAL_UPLOAD_SIGNING_HMAC_KEY": (
                "Dg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4"
            )
        },
    )

    assert runtime["environment"] == "development"
    assert runtime["database"]["mode"] == "postgresql"
    assert runtime["security"]["identity_mode"] == "development_mock"
    assert runtime["ai"]["provider"] == "mock"
    assert runtime["resume_rendering"]["adapter"] == "mock"
    assert runtime["interview"]["realtime"]["signing_keyring"] == {
        "active_key_id": None,
        "keys": {},
    }
    assert runtime["interview"]["realtime"]["signaling_url"] is None


def test_development_projection_preserves_explicit_interview_realtime_config(
    tmp_path: Path,
) -> None:
    """@brief development 投影不得丢失持久的 realtime key ID / Development projection preserves an explicit realtime key ID.

    @param tmp_path pytest 临时目录 / pytest temporary directory.
    """

    source_path = _bootstrap_config(tmp_path)
    source = _load_mapping(source_path)
    source["interview"]["realtime"].update(
        {
            "signing_keyring": {
                "active_key_id": "interview-dev-2026-07",
                "keys": {
                    "interview-dev-2026-07": (
                        "FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQ"
                    )
                },
            },
            "signaling_url": "wss://realtime.hmalliances.org/v2/interview",
        }
    )
    source_path.write_text(json.dumps(source), encoding="utf-8")

    runtime = build_runtime_config(
        source_path,
        {
            "AIWS_KNOWLEDGE_LOCAL_UPLOAD_SIGNING_HMAC_KEY": (
                "Dg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4"
            )
        },
    )

    assert runtime["interview"]["realtime"]["signing_keyring"][
        "active_key_id"
    ] == "interview-dev-2026-07"
    assert runtime["interview"]["realtime"]["signaling_url"] == (
        "wss://realtime.hmalliances.org/v2/interview"
    )


def test_docker_dbinit_only_changes_connection_endpoint() -> None:
    """@brief Docker dbinit 只能改变连接端点 / Docker dbinit may only change the connection endpoint."""

    local = _load_mapping(PROJECT_ROOT / "dbinit.jsonc")
    docker = _load_mapping(PROJECT_ROOT / "deploy/docker/dbinit.jsonc")

    assert docker["database_connection"] == {"host": "postgres", "port": 5432}
    assert docker["database_administration"] == local["database_administration"]


def test_nginx_exposes_only_the_frozen_v2_tls_surface() -> None:
    """@brief Nginx 对齐 :8022→:9000 且只公开 OAuth/Identity/API V2 / Nginx aligns :8022-to-:9000 and exposes only OAuth, Identity, and API V2."""

    source = (PROJECT_ROOT / "deploy/nginx/ai-job-workspace.conf").read_text(
        encoding="utf-8"
    )

    assert "listen 8022 ssl http2;" in source
    assert "server_name api.hmalliances.org;" in source
    assert "ssl_certificate /etc/aiws/tls/fullchain.pem;" in source
    assert "ssl_certificate_key /etc/aiws/tls/privkey.pem;" in source
    assert "ssl_protocols TLSv1.2 TLSv1.3;" in source
    assert "Strict-Transport-Security" in source
    assert "server 127.0.0.1:9000;" in source
    for boundary in (
        "location = /.well-known/openid-configuration",
        "location = /.well-known/oauth-protected-resource",
        "location /oauth/",
        "location /identity/v2/",
        "location = /userinfo",
        "location /api/v2/",
    ):
        assert boundary in source
    assert "location /api/v1/ { return 404; }" in source
    assert "location ~ ^/api/v2/workspaces/[^/]+/events$" in source
    assert "proxy_buffering off;" in source
    assert "proxy_set_header Forwarded \"\";" in source
    assert "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for" not in source


def test_runtime_image_contains_the_declared_sandboxed_renderer_capability() -> None:
    """@brief 生产镜像同时提供 XeLaTeX、CJK 字体与 OS sandbox / Runtime image ships XeLaTeX, CJK fonts, and the OS sandbox together."""

    source = (PROJECT_ROOT / "Dockerfile").read_text(encoding="utf-8")

    for package in ("bubblewrap", "fonts-noto-cjk", "libseccomp2", "texlive-xetex"):
        assert package in source


def test_runtime_services_bound_the_process_tree_with_cgroup_pids() -> None:
    """@brief XeLaTeX 子进程树由容器 cgroup 限制 / Bound the XeLaTeX process tree with the container cgroup."""

    source = (PROJECT_ROOT / "compose.yaml").read_text(encoding="utf-8")

    assert "x-aiws-runtime-service: &aiws-runtime-service" in source
    assert "  pids_limit: 256\n" in source
    assert "  cap_drop:\n    - ALL\n" in source


def test_runtime_image_builds_from_the_fixed_v2_contract_revision() -> None:
    """@brief 镜像构建显式复制父仓库固定的 V2 契约 / Image build explicitly copies the parent-pinned V2 contract.

    @return 无返回值 / No return value.
    """

    source = (PROJECT_ROOT / "Dockerfile").read_text(encoding="utf-8")

    assert "COPY workspace-shared-docs/contracts/v2/schema.jsonc" in source
    assert "./workspace-shared-docs/contracts/v2/schema.jsonc" in source


@pytest.mark.parametrize("environment", ("staging", "production"))
@pytest.mark.parametrize("identity_mode", ("development_mock", "trusted_proxy_hmac"))
def test_deployed_container_rejects_non_disabled_legacy_identity(
    tmp_path: Path,
    environment: str,
    identity_mode: str,
) -> None:
    """@brief 部署运行时只接受关闭的 legacy identity 端口 / Deployed runtimes accept only a disabled legacy-identity port.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @param environment 部署环境 / Deployed environment.
    @param identity_mode 被拒绝的旧身份模式 / Rejected legacy identity mode.
    """

    source_path = _bootstrap_config(tmp_path)
    environ = _container_environment()
    environ["AIWS_ENVIRONMENT"] = environment
    environ["AIWS_IDENTITY_MODE"] = identity_mode

    with pytest.raises(ConfigurationError, match="AIWS_IDENTITY_MODE must be disabled"):
        build_runtime_config(source_path, environ)


@pytest.mark.parametrize("environment", ("staging", "production"))
def test_deployed_container_rejects_unconsumed_legacy_identity_hmac_secret(
    tmp_path: Path,
    environment: str,
) -> None:
    """@brief 部署投影拒绝已无消费者的 legacy HMAC secret / Deployment projection rejects an unconsumed legacy HMAC secret.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    @param environment 部署环境 / Deployed environment.
    """

    source_path = _bootstrap_config(tmp_path)
    environ = _container_environment()
    environ["AIWS_ENVIRONMENT"] = environment
    environ["AIWS_TRUSTED_PROXY_HMAC_SECRET"] = (
        "unused-legacy-proxy-secret-with-at-least-32-bytes"
    )

    with pytest.raises(ConfigurationError, match="is not consumed"):
        build_runtime_config(source_path, environ)


def test_production_container_requires_cursor_secret(tmp_path: Path) -> None:
    """@brief 多 worker cursor 缺少共享密钥时必须 fail closed / Production fails closed without a shared cursor secret.

    @param tmp_path pytest 临时目录 / Pytest temporary directory.
    """
    source_path = _bootstrap_config(tmp_path)
    environ = _container_environment()
    del environ["AIWS_CURSOR_HMAC_SECRET"]

    with pytest.raises(ConfigurationError, match="AIWS_CURSOR_HMAC_SECRET"):
        build_runtime_config(source_path, environ)


@pytest.mark.parametrize(
    "missing_name",
    (
        "AIWS_SENSITIVE_IDEMPOTENCY_HMAC_SECRET",
        "AIWS_IDENTITY_EMAIL_ACTIVE_KEY_ID",
        "AIWS_IDENTITY_EMAIL_ENCRYPTION_KEYS",
        "AIWS_IDENTITY_EMAIL_RATE_LIMIT_HMAC_KEY",
        "AIWS_IDENTITY_EMAIL_FROM_ADDRESS",
        "AIWS_IDENTITY_EMAIL_SMTP_HOST",
        "AIWS_KNOWLEDGE_PROVIDER_SESSION_ACTIVE_KEY_ID",
        "AIWS_KNOWLEDGE_PROVIDER_SESSION_KEYS",
        "AIWS_KNOWLEDGE_CREDENTIAL_ACTIVE_KEY_ID",
        "AIWS_KNOWLEDGE_CREDENTIAL_KEYS",
        "AIWS_KNOWLEDGE_CREDENTIAL_FINGERPRINT_HMAC_KEY",
        "AIWS_KNOWLEDGE_CREDENTIAL_REFERENCE_HMAC_KEY",
        "AIWS_KNOWLEDGE_S3_ENDPOINT",
        "AIWS_KNOWLEDGE_S3_REGION",
        "AIWS_KNOWLEDGE_S3_BUCKET",
        "AIWS_KNOWLEDGE_S3_ACCESS_KEY_ID",
        "AIWS_KNOWLEDGE_S3_SECRET_ACCESS_KEY",
        "AIWS_KNOWLEDGE_SOURCE_ALLOWED_HOST_PATTERNS",
        "AIWS_INTERVIEW_REALTIME_ACTIVE_KEY_ID",
        "AIWS_INTERVIEW_REALTIME_SIGNING_KEYS",
        "AIWS_INTERVIEW_SIGNALING_URL",
        "AIWS_AI_PROVIDER",
        "AIWS_AI_MODEL",
        "AIWS_AI_BASE_URL",
        "AIWS_AI_DATA_REGION",
        "AIWS_AI_EMBEDDING_PROVIDER",
        "AIWS_AI_EMBEDDING_MODEL",
        "AIWS_AI_EMBEDDING_MODEL_REVISION",
        "AIWS_AI_EMBEDDING_DIMENSION",
        "AIWS_LLM_API_KEY",
        "AIWS_RESUME_RENDERER_ADAPTER",
    ),
)
def test_production_container_requires_distributed_security_keys(
    tmp_path: Path,
    missing_name: str,
) -> None:
    """@brief production 缺任一多 worker key 都 fail closed / Production fails closed without any distributed key.

    @param tmp_path pytest 临时目录 / pytest temporary directory.
    @param missing_name 本 case 删除的环境变量 / Environment variable removed in this case.
    """

    source_path = _bootstrap_config(tmp_path)
    environ = _container_environment()
    del environ[missing_name]

    with pytest.raises(ConfigurationError, match=missing_name):
        build_runtime_config(source_path, environ)


@pytest.mark.parametrize(
    "malformed",
    ('[]', '{}', '{"key":""}', 'not-json'),
)
def test_identity_email_keyring_environment_requires_nonempty_string_mapping(
    tmp_path: Path,
    malformed: str,
) -> None:
    """@brief keyring env 拒绝错误 JSON shape 且不回显内容 / Keyring env rejects malformed shapes without echoing values.

    @param tmp_path pytest 临时目录 / pytest temporary directory.
    @param malformed 非法 keyring JSON / Invalid keyring JSON.
    """

    source_path = _bootstrap_config(tmp_path)
    environ = _container_environment()
    environ["AIWS_IDENTITY_EMAIL_ENCRYPTION_KEYS"] = malformed

    with pytest.raises(ConfigurationError, match="must be a JSON string mapping") as error:
        build_runtime_config(source_path, environ)
    assert malformed not in str(error.value)
